In [3]:
import pandas as pd
import numpy as np

In [9]:
trainset = pd.read_csv('../../data/kaggle+twitter.csv')
trainset

Unnamed: 0  type                                               flat
0              0  INFJ  moment sportscent top ten play prank life chan...
1              1  ENTP  find lack post alarm sex bore posit often exam...
2              2  INTP  good one cours say know bless cur absolut posi...
3              3  INTJ  dear enjoy convers day esoter gab natur univer...
4              4  ENTJ  fire anoth silli misconcept approach logic go ...
...          ...   ...                                                ...
8771        8771  ISFP  fight ensur power medium corpor planet treat f...
8772        8772  ISFP  face_with_tears_of_joy sign_of_the_horns_mediu...
8773        8773  INTJ  cst___ video light venu everyth power realli a...
8774        8774  INFJ  support affect elementari school shoot uvald t...
8775        8775  ENFP  hear someon open bag chip year marriag handsom...

[8776 rows x 3 columns]

In [21]:
list_posts = []
for i in range(len(trainset)):
    post = trainset.loc[i, 'flat']
    list_posts.append(post)
list_posts = np.array(list_posts)

In [22]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

# Vectorizing the database posts to a matrix of token counts for the model
cntizer = CountVectorizer() 
                        
# the feature should be made of word n-gram 
# Learn the vocabulary dictionary and return term-document matrix
print("Using CountVectorizer :")
X_cnt = cntizer.fit_transform(list_posts)
col_name = cntizer.get_feature_names_out()   # 紀錄 sparse matrix 的字分別是哪些字


# For the Standardization or Feature Scaling Stage :-
# Transform the count matrix to a normalized tf or tf-idf representation
tfizer = TfidfTransformer()

# Learn the idf vector (fit) and transform a count matrix to a tf-idf representation
print("\nUsing Tf-idf :")

print("Now the dataset size is as below")
X_tfidf =  tfizer.fit_transform(X_cnt).toarray()
X_tfidf.shape

Using CountVectorizer :

Using Tf-idf :
Now the dataset size is as below


(8776, 132543)

In [12]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=100)
result = svd.fit_transform(X_tfidf)
result

array([[ 2.29552665e-01, -2.89886743e-02, -4.59738607e-02, ...,
        -1.66633285e-03, -1.23848509e-02, -1.09445092e-02],
       [ 3.60625669e-01,  1.24753477e-02, -3.40479105e-04, ...,
         3.73606198e-03, -8.52255963e-03, -2.89700568e-02],
       [ 3.27324445e-01, -3.09335700e-02, -4.04488445e-02, ...,
        -1.41624581e-02, -3.70646609e-02,  2.24247394e-02],
       ...,
       [ 2.15979990e-01, -7.89459044e-02, -2.60553941e-02, ...,
         2.98201630e-02,  7.92356995e-03, -3.36127923e-02],
       [ 1.90536688e-01, -9.16637045e-02, -9.06452688e-03, ...,
         3.78216694e-02,  1.29135565e-02, -1.68493310e-02],
       [ 2.57942925e-01, -1.32508831e-01, -2.37310305e-02, ...,
        -1.95025416e-02, -1.53650549e-02,  2.66041597e-02]])

In [13]:
trainingdf = pd.DataFrame(result)
trainingdf

0         1         2         3         4         5         6   \
0     0.229553 -0.028989 -0.045974  0.066428 -0.057229  0.079087  0.003797   
1     0.360626  0.012475 -0.000340  0.022319 -0.006080  0.034986 -0.060051   
2     0.327324 -0.030934 -0.040449  0.026471 -0.027835  0.053572 -0.016258   
3     0.386935  0.149640 -0.024360  0.000873 -0.044892 -0.022475  0.024637   
4     0.311357 -0.012648 -0.029454  0.000107 -0.058061 -0.068007  0.012177   
...        ...       ...       ...       ...       ...       ...       ...   
8771  0.145925 -0.076368 -0.018983  0.087965 -0.055252  0.158276 -0.065960   
8772  0.309016 -0.162717  0.062645  0.110800 -0.051515  0.229390 -0.076628   
8773  0.215980 -0.078946 -0.026055  0.103513 -0.076049  0.146495 -0.085867   
8774  0.190537 -0.091664 -0.009065  0.090745 -0.065706  0.151323 -0.076247   
8775  0.257943 -0.132509 -0.023731  0.106114 -0.050041  0.209582 -0.094936   

            7         8         9   ...        90        91        92  \
0     0.032540 -0.009948  0.038943  ...  0.002499 -0.008046 -0.029300   
1    -0.010684 -0.040281 -0.011646  ... -0.000149  0.043186  0.026046   
2    -0.024198 -0.007088 -0.001764  ...  0.020128 -0.041694 -0.038324   
3     0.058961  0.065796 -0.054293  ... -0.001368 -0.035642 -0.016188   
4     0.038274 -0.059952 -0.069083  ... -0.016169  0.027091 -0.004162   
...        ...       ...       ...  ...       ...       ...       ...   
8771 -0.140311  0.064631 -0.060026  ...  0.007848 -0.014100  0.002095   
8772 -0.190612  0.077283 -0.136714  ...  0.034406  0.015390 -0.026552   
8773 -0.130801  0.047882 -0.072179  ... -0.025495  0.000020  0.017968   
8774 -0.135038  0.059777 -0.093521  ... -0.035706  0.005411  0.016421   
8775 -0.147726  0.071301 -0.057039  ...  0.026740 -0.023886  0.007499   

            93        94        95        96        97        98        99  
0     0.010658  0.020756  0.060105 -0.030927 -0.001666 -0.012385 -0.010945  
1     0.021477  0.016897 -0.025803 -0.027270  0.003736 -0.008523 -0.028970  
2    -0.030900  0.012010 -0.024744 -0.012335 -0.014162 -0.037065  0.022425  
3    -0.003154  0.017735 -0.019992  0.013362 -0.001379  0.006080  0.028174  
4     0.017459 -0.003076 -0.007075 -0.010500 -0.002241  0.003513  0.006893  
...        ...       ...       ...       ...       ...       ...       ...  
8771  0.023920  0.001678  0.007000 -0.015666  0.005461  0.008498  0.008782  
8772  0.023591  0.016340 -0.005890  0.012111  0.025508  0.020339 -0.009905  
8773  0.008183  0.012583 -0.024358  0.005259  0.029820  0.007924 -0.033613  
8774  0.019765  0.038883 -0.020577  0.000425  0.037822  0.012914 -0.016849  
8775 -0.021123 -0.024248  0.005490 -0.006634 -0.019503 -0.015365  0.026604  

[8776 rows x 100 columns]

### Data = raw data

In [16]:
label = trainset.loc[:,['type']]
from sklearn.preprocessing import LabelEncoder
Y = LabelEncoder().fit_transform(label)   # Y before train-test-split

# train-test-split
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(trainingdf, Y, test_size=0.33, random_state=42)


# grid search
n_estimators = [int(x) for x in np.linspace(start=100, stop=1000, num=10)]
learning_rate=[round(float(x),2) for x in np.linspace(start=0.1, stop=0.2, num=5)]

best_nest = 0
best_lr = 0
best_acc=0

for nest in n_estimators:
    local_acc = 0
    local_lr = 0
    for lr in learning_rate:
        param = {}
        param['n_estimators'] = nest
        param['max_depth'] = 2
        param['learning_rate'] = lr

        xgb = XGBClassifier(**param)
        xgb_model = xgb.fit(X_train,y_train)

        Y_pred = xgb_model.predict(X_valid)
        predictions = [round(value) for value in Y_pred]

        # evaluate predictions
        accuracy = accuracy_score(y_valid, predictions)

        if accuracy > local_acc:
            local_acc = accuracy
            local_lr = lr

        if accuracy > best_acc:
            best_acc = accuracy
            best_nest = nest
            best_lr = lr
    
    print(f'n_estimator = {nest}, learning_rate = {local_lr}, best accuracy = {local_acc} ')

print(f'Result : best n_estimator = {best_nest}, best learning_rate = {best_lr}, best accuracy = {best_acc} ')
print('-----------------------------------------------------------')


#XG boost Classifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

param = {}

param['n_estimators'] = best_nest
param['max_depth'] = 2
param['learning_rate'] = best_lr

xgb = XGBClassifier(**param)
xgb_model = xgb.fit(X_train,y_train)

Y_pred = xgb_model.predict(X_valid)
predictions = [round(value) for value in Y_pred]

# evaluate predictions
accuracy = accuracy_score(y_valid, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

precision_mi = precision_score(y_valid, predictions, average='micro')
print("Micro Precision: %.2f%%" % (precision_mi * 100.0))
precision_ma = precision_score(y_valid, predictions, average='macro')
print("Macro Precision: %.2f%%" % (precision_ma * 100.0))

recall_mi = recall_score(y_valid, predictions, average='micro')
print("Micro Recall: %.2f%%" % (recall_mi * 100.0))
recall_ma = recall_score(y_valid, predictions, average='macro')
print("Macro Recall: %.2f%%" % (recall_ma * 100.0))

f1score_mi = f1_score(y_valid, predictions, average='micro')
print("Micro F1score: %.2f%%" % (f1score_mi * 100.0))
f1score_ma = f1_score(y_valid, predictions, average='macro')
print("Macro F1score: %.2f%%" % (f1score_ma * 100.0))

/Users/chenenying/opt/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


n_estimator = 100, learning_rate = 0.18, best accuracy = 0.3279254401104591 
n_estimator = 200, learning_rate = 0.12, best accuracy = 0.3341387642388678 
n_estimator = 300, learning_rate = 0.12, best accuracy = 0.33551950293406974 
n_estimator = 400, learning_rate = 0.12, best accuracy = 0.33931653434587505 
n_estimator = 500, learning_rate = 0.15, best accuracy = 0.3403520883672765 
n_estimator = 600, learning_rate = 0.1, best accuracy = 0.33897134967207454 
n_estimator = 700, learning_rate = 0.1, best accuracy = 0.33724542630307214 
n_estimator = 800, learning_rate = 0.1, best accuracy = 0.3341387642388678 
n_estimator = 900, learning_rate = 0.1, best accuracy = 0.3334483948912668 
n_estimator = 1000, learning_rate = 0.12, best accuracy = 0.3324128408698654 
Result : best n_estimator = 500, best learning_rate = 0.15, best accuracy = 0.3403520883672765 
-----------------------------------------------------------
Accuracy: 34.04%
Micro Precision: 34.04%
Macro Precision: 22.57%
Micro Re

/Users/chenenying/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
label = trainset.loc[:,['type']]
from sklearn.preprocessing import LabelEncoder
Y = LabelEncoder().fit_transform(label)   # Y before train-test-split

# train-test-split
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(trainingdf, Y, test_size=0.33, random_state=42)

# SMOTE
from imblearn.over_sampling import SMOTE
X_re, y_re = SMOTE(random_state=42).fit_resample(X_train, y_train)


# grid search
n_estimators = [int(x) for x in np.linspace(start=100, stop=1000, num=10)]
learning_rate=[round(float(x),2) for x in np.linspace(start=0.1, stop=0.2, num=5)]

best_nest = 0
best_lr = 0
best_acc=0

for nest in n_estimators:
    local_acc = 0
    local_lr = 0
    for lr in learning_rate:
        param = {}
        param['n_estimators'] = nest
        param['max_depth'] = 2
        param['learning_rate'] = lr

        xgb = XGBClassifier(**param)
        xgb_model = xgb.fit(X_re,y_re)

        Y_pred = xgb_model.predict(X_valid)
        predictions = [round(value) for value in Y_pred]

        # evaluate predictions
        accuracy = accuracy_score(y_valid, predictions)

        if accuracy > local_acc:
            local_acc = accuracy
            local_lr = lr

        if accuracy > best_acc:
            best_acc = accuracy
            best_nest = nest
            best_lr = lr
    
    print(f'n_estimator = {nest}, learning_rate = {local_lr}, best accuracy = {local_acc} ')

print(f'Result : best n_estimator = {best_nest}, best learning_rate = {best_lr}, best accuracy = {best_acc} ')
print('-----------------------------------------------------------')



#XG boost Classifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

param = {}

param['n_estimators'] = best_nest # after tunning
param['max_depth'] = 2
param['learning_rate'] = best_lr # after tunning

xgb = XGBClassifier(**param)
xgb_model = xgb.fit(X_re, y_re)

Y_pred = xgb_model.predict(X_valid)
predictions = [round(value) for value in Y_pred]

print('Result for XGboost after grid search (remove_MBTI = True, Model = XGboost, data = SMOTE)')
# evaluate predictions
accuracy = accuracy_score(y_valid, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

precision_mi = precision_score(y_valid, predictions, average='micro')
print("Micro Precision: %.2f%%" % (precision_mi * 100.0))
precision_ma = precision_score(y_valid, predictions, average='macro')
print("Macro Precision: %.2f%%" % (precision_ma * 100.0))

recall_mi = recall_score(y_valid, predictions, average='micro')
print("Micro Recall: %.2f%%" % (recall_mi * 100.0))
recall_ma = recall_score(y_valid, predictions, average='macro')
print("Macro Recall: %.2f%%" % (recall_ma * 100.0))

f1score_mi = f1_score(y_valid, predictions, average='micro')
print("Micro F1score: %.2f%%" % (f1score_mi * 100.0))
f1score_ma = f1_score(y_valid, predictions, average='macro')
print("Macro F1score: %.2f%%" % (f1score_ma * 100.0))

/Users/chenenying/opt/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


n_estimator = 100, learning_rate = 0.2, best accuracy = 0.26234035208836726 
n_estimator = 200, learning_rate = 0.2, best accuracy = 0.28408698653779774 
n_estimator = 300, learning_rate = 0.2, best accuracy = 0.2989299275112185 
n_estimator = 400, learning_rate = 0.2, best accuracy = 0.3016914049016224 
n_estimator = 500, learning_rate = 0.18, best accuracy = 0.30583362098722816 
n_estimator = 600, learning_rate = 0.2, best accuracy = 0.30583362098722816 
n_estimator = 700, learning_rate = 0.2, best accuracy = 0.3113565757680359 
n_estimator = 800, learning_rate = 0.18, best accuracy = 0.3106662064204349 
n_estimator = 900, learning_rate = 0.15, best accuracy = 0.3110113910942354 
n_estimator = 1000, learning_rate = 0.12, best accuracy = 0.3161891612012427 
Result : best n_estimator = 1000, best learning_rate = 0.12, best accuracy = 0.3161891612012427 
-----------------------------------------------------------
Result for XGboost after grid search (remove_MBTI = True, Model = XGboost,

### Combine 4 binary model

In [16]:
data = pd.read_csv('../../data/kaggle+twitter.csv')
def get_types(row):
    t=row['type']

    I = 0; N = 0
    T = 0; J = 0
    
    if t[0] == 'I': I = 1
    elif t[0] == 'E': I = 0
    else: print('I-E not found') 
        
    if t[1] == 'N': N = 1
    elif t[1] == 'S': N = 0
    else: print('N-S not found')
        
    if t[2] == 'T': T = 1
    elif t[2] == 'F': T = 0
    else: print('T-F not found')
        
    if t[3] == 'J': J = 1
    elif t[3] == 'P': J = 0
    else: print('J-P not found')
    return pd.Series( {'IE':I, 'NS':N , 'TF': T, 'JP': J }) 

data = data.join(data.apply (lambda row: get_types (row),axis=1))
data

Unnamed: 0  type                                               flat  IE  \
0              0  INFJ  moment sportscent top ten play prank life chan...   1   
1              1  ENTP  find lack post alarm sex bore posit often exam...   0   
2              2  INTP  good one cours say know bless cur absolut posi...   1   
3              3  INTJ  dear enjoy convers day esoter gab natur univer...   1   
4              4  ENTJ  fire anoth silli misconcept approach logic go ...   0   
...          ...   ...                                                ...  ..   
8771        8771  ISFP  fight ensur power medium corpor planet treat f...   1   
8772        8772  ISFP  face_with_tears_of_joy sign_of_the_horns_mediu...   1   
8773        8773  INTJ  cst___ video light venu everyth power realli a...   1   
8774        8774  INFJ  support affect elementari school shoot uvald t...   1   
8775        8775  ENFP  hear someon open bag chip year marriag handsom...   0   

      NS  TF  JP  
0      1   0   1  
1      1   1   0  
2      1   1   0  
3      1   1   1  
4      1   1   1  
...   ..  ..  ..  
8771   0   0   0  
8772   0   0   0  
8773   1   1   1  
8774   1   0   1  
8775   1   0   0  

[8776 rows x 7 columns]

In [17]:
print ("Introversion (I) /  Extroversion (E):\t", data['IE'].value_counts()[0], " / ", data['IE'].value_counts()[1])
print ("Intuition (N) / Sensing (S):\t\t", data['NS'].value_counts()[0], " / ", data['NS'].value_counts()[1])
print ("Thinking (T) / Feeling (F):\t\t", data['TF'].value_counts()[0], " / ", data['TF'].value_counts()[1])
print ("Judging (J) / Perceiving (P):\t\t", data['JP'].value_counts()[0], " / ", data['JP'].value_counts()[1])

Introversion (I) /  Extroversion (E):	 2057  /  6719
Intuition (N) / Sensing (S):		 1268  /  7508
Thinking (T) / Feeling (F):		 4757  /  4019
Judging (J) / Perceiving (P):		 5311  /  3465


In [18]:
# Splitting the MBTI personality into 4 letters and binarizing it

b_Pers = {'I':0, 'E':1, 'N':0, 'S':1, 'F':0, 'T':1, 'J':0, 'P':1}
b_Pers_list = [{0:'I', 1:'E'}, {0:'N', 1:'S'}, {0:'F', 1:'T'}, {0:'J', 1:'P'}]

def translate_personality(personality):
    # transform mbti to binary vector
    return [b_Pers[l] for l in personality]

#To show result output for personality prediction
def translate_back(personality):
    # transform binary vector to mbti personality
    s = ""
    for i, l in enumerate(personality):
        s += b_Pers_list[i][l]
    return s

list_personality_bin = np.array([translate_personality(p) for p in data.type])
print("Binarize MBTI list: \n%s" % list_personality_bin)

Binarize MBTI list: 
[[0 0 0 0]
 [1 0 1 1]
 [0 0 1 1]
 ...
 [0 0 1 0]
 [0 0 0 0]
 [1 0 0 1]]


In [19]:
list_personality=[]
for row in data.iterrows():
    type_labelized = translate_personality(row[1].type) #or use lab_encoder.transform([row[1].type])[0]
    list_personality.append(type_labelized)
list_personality = np.array(list_personality)
list_personality.shape

(8776, 4)

In [20]:
personality_type = [ "IE: Introversion (I) / Extroversion (E)", "NS: Intuition (N) / Sensing (S)", 
                   "FT: Feeling (F) / Thinking (T)", "JP: Judging (J) / Perceiving (P)"  ]

for l in range(len(personality_type)):
    print(personality_type[l])

IE: Introversion (I) / Extroversion (E)
NS: Intuition (N) / Sensing (S)
FT: Feeling (F) / Thinking (T)
JP: Judging (J) / Perceiving (P)


In [23]:
personality_type = [ "IE: Introversion (I) / Extroversion (E)", "NS: Intuition (N) / Sensing (S)", 
                   "FT: Feeling (F) / Thinking (T)", "JP: Judging (J) / Perceiving (P)"  ]

for l in range(len(personality_type)):
    print(personality_type[l])
X_tfidf.shape

from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=100)
X = svd.fit_transform(X_tfidf)

IE: Introversion (I) / Extroversion (E)
NS: Intuition (N) / Sensing (S)
FT: Feeling (F) / Thinking (T)
JP: Judging (J) / Perceiving (P)


#### XGBoost

In [42]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

X_train, X_test, y_train, y_test = train_test_split(X, list_personality, test_size=0.33, random_state=42)


final_pred = np.zeros((X_test.shape[0], 4)) # 紀錄 4 個 model 分別預測病combine後的 MBTI 結果

# XGBoost Model create
for l in range(len(personality_type)):
    
    Y = y_train[:,l]


    # fit model on training data
    param = {}

    param['n_estimators'] = 700 # after tunning
    param['max_depth'] = 2
    param['learning_rate'] = 0.12 # after tunning

    model = XGBClassifier(**param)
    model.fit(X_train, y_train[:,l])

    # make predictions for test data
    y_pred = model.predict(X_test)

    # 將四個預測結果合併成最後 MBTI 結果
    for j in range(len(y_pred)):
        final_pred[j][l] = y_pred[j]


    # predictions = [round(value) for value in y_pred]
    # # evaluate predictions
    # accuracy = accuracy_score(y_test, predictions)
    
    print(personality_type[l])
    print(y_pred)

accuracy = accuracy_score(y_test, final_pred)
print(f'The final Accuracy is : {accuracy}')

precision_we = precision_score(y_test, final_pred, average='weighted')
print("Weighted Precision: %.2f%%" % (precision_we * 100.0))
precision_ma = precision_score(y_test, final_pred, average='macro')
print("Macro Precision: %.2f%%" % (precision_ma * 100.0))

recall_we = recall_score(y_test, final_pred, average='weighted')
print("Weighted Recall: %.2f%%" % (recall_we * 100.0))
recall_ma = recall_score(y_test, final_pred, average='macro')
print("Macro Recall: %.2f%%" % (recall_ma * 100.0))

f1score_we = f1_score(y_test, final_pred, average='weighted')
print("Weighted F1score: %.2f%%" % (f1score_we * 100.0))
f1score_ma = f1_score(y_test, final_pred, average='macro')
print("Macro F1score: %.2f%%" % (f1score_ma * 100.0))

IE: Introversion (I) / Extroversion (E)
[0 0 0 ... 0 0 0]
NS: Intuition (N) / Sensing (S)
[0 0 0 ... 0 0 0]
FT: Feeling (F) / Thinking (T)
[1 1 0 ... 0 1 0]
JP: Judging (J) / Perceiving (P)
[1 0 1 ... 0 0 0]
The final Accuracy is : 0.3234380393510528
Weighted Precision: 66.05%
Macro Precision: 61.68%
Weighted Recall: 60.75%
Macro Recall: 45.88%
Weighted F1score: 60.71%
Macro F1score: 48.71%


#### Logistic Regression

In [41]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, list_personality, test_size=0.33, random_state=42)


final_pred = np.zeros((X_test.shape[0], 4)) # 紀錄 4 個 model 分別預測病combine後的 MBTI 結果

# XGBoost Model create
for l in range(len(personality_type)):
    
    Y = y_train[:,l]


    clf = LogisticRegression(random_state=0).fit(X_train, y_train[:,l])

    # make predictions for test data
    y_pred = clf.predict(X_test)

    # 將四個預測結果合併成最後 MBTI 結果
    for j in range(len(y_pred)):
        final_pred[j][l] = y_pred[j]


    # predictions = [round(value) for value in y_pred]
    # # evaluate predictions
    # accuracy = accuracy_score(y_test, predictions)
    
    print(personality_type[l])
    print(y_pred)

accuracy = accuracy_score(y_test, final_pred)
print(f'The final Accuracy is : {accuracy}')

precision_we = precision_score(y_test, final_pred, average='weighted')
print("Weighted Precision: %.2f%%" % (precision_we * 100.0))
precision_ma = precision_score(y_test, final_pred, average='macro')
print("Macro Precision: %.2f%%" % (precision_ma * 100.0))

recall_we = recall_score(y_test, final_pred, average='weighted')
print("Weighted Recall: %.2f%%" % (recall_we * 100.0))
recall_ma = recall_score(y_test, final_pred, average='macro')
print("Macro Recall: %.2f%%" % (recall_ma * 100.0))

f1score_we = f1_score(y_test, final_pred, average='weighted')
print("Weighted F1score: %.2f%%" % (f1score_we * 100.0))
f1score_ma = f1_score(y_test, final_pred, average='macro')
print("Macro F1score: %.2f%%" % (f1score_ma * 100.0))

IE: Introversion (I) / Extroversion (E)
[0 0 0 ... 0 0 0]
NS: Intuition (N) / Sensing (S)
[0 0 0 ... 0 0 0]
FT: Feeling (F) / Thinking (T)
[1 1 0 ... 0 1 0]
JP: Judging (J) / Perceiving (P)
[1 1 1 ... 1 0 0]
The final Accuracy is : 0.329996548153262
Weighted Precision: 70.20%
Macro Precision: 69.62%
Weighted Recall: 62.61%
Macro Recall: 43.67%
Weighted F1score: 58.98%
Macro F1score: 43.15%


#### SVM

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

X_train, X_test, y_train, y_test = train_test_split(X, list_personality, test_size=0.33, random_state=42)


final_pred = np.zeros((X_test.shape[0], 4)) # 紀錄 4 個 model 分別預測病combine後的 MBTI 結果

# XGBoost Model create
for l in range(len(personality_type)):
    
    Y = y_train[:,l]


    clf = SVC(kernel='linear')
    clf.fit(X_train,y_train[:,l])

    # make predictions for test data
    y_pred = clf.predict(X_test)

    # 將四個預測結果合併成最後 MBTI 結果
    for j in range(len(y_pred)):
        final_pred[j][l] = y_pred[j]


    # predictions = [round(value) for value in y_pred]
    # # evaluate predictions
    # accuracy = accuracy_score(y_test, predictions)
    
    print(personality_type[l])
    print(y_pred)

accuracy = accuracy_score(y_test, final_pred)
print(f'The final Accuracy is : {accuracy}')

precision_we = precision_score(y_test, final_pred, average='weighted')
print("Weighted Precision: %.2f%%" % (precision_we * 100.0))
precision_ma = precision_score(y_test, final_pred, average='macro')
print("Macro Precision: %.2f%%" % (precision_ma * 100.0))

recall_we = recall_score(y_test, final_pred, average='weighted')
print("Weighted Recall: %.2f%%" % (recall_we * 100.0))
recall_ma = recall_score(y_test, final_pred, average='macro')
print("Macro Recall: %.2f%%" % (recall_ma * 100.0))

f1score_we = f1_score(y_test, final_pred, average='weighted')
print("Weighted F1score: %.2f%%" % (f1score_we * 100.0))
f1score_ma = f1_score(y_test, final_pred, average='macro')
print("Macro F1score: %.2f%%" % (f1score_ma * 100.0))

IE: Introversion (I) / Extroversion (E)
[0 0 0 ... 0 0 0]
NS: Intuition (N) / Sensing (S)
[0 0 0 ... 0 0 0]
FT: Feeling (F) / Thinking (T)
[1 1 0 ... 0 1 0]
JP: Judging (J) / Perceiving (P)
[1 1 1 ... 1 1 0]
The final Accuracy is : 0.3224024853296514
Weighted Precision: 57.10%
Macro Precision: 47.18%
Weighted Recall: 63.44%
Macro Recall: 42.81%
Weighted F1score: 57.03%
Macro F1score: 39.38%


/Users/chenenying/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/chenenying/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#### NB 

In [39]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, list_personality, test_size=0.33, random_state=42)


final_pred = np.zeros((X_test.shape[0], 4)) # 紀錄 4 個 model 分別預測病combine後的 MBTI 結果

# XGBoost Model create
for l in range(len(personality_type)):
    
    Y = y_train[:,l]

    gnb = GaussianNB()
    y_pred = gnb.fit(X_train,y_train[:,l]).predict(X_test)

    # 將四個預測結果合併成最後 MBTI 結果
    for j in range(len(y_pred)):
        final_pred[j][l] = y_pred[j]


    # predictions = [round(value) for value in y_pred]
    # # evaluate predictions
    # accuracy = accuracy_score(y_test, predictions)
    
    print(personality_type[l])
    print(y_pred)

accuracy = accuracy_score(y_test, final_pred)
print(f'The final Accuracy is : {accuracy}')

precision_we = precision_score(y_test, final_pred, average='weighted')
print("Weighted Precision: %.2f%%" % (precision_we * 100.0))
precision_ma = precision_score(y_test, final_pred, average='macro')
print("Macro Precision: %.2f%%" % (precision_ma * 100.0))

recall_we = recall_score(y_test, final_pred, average='weighted')
print("Weighted Recall: %.2f%%" % (recall_we * 100.0))
recall_ma = recall_score(y_test, final_pred, average='macro')
print("Macro Recall: %.2f%%" % (recall_ma * 100.0))

f1score_we = f1_score(y_test, final_pred, average='weighted')
print("Weighted F1score: %.2f%%" % (f1score_we * 100.0))
f1score_ma = f1_score(y_test, final_pred, average='macro')
print("Macro F1score: %.2f%%" % (f1score_ma * 100.0))

IE: Introversion (I) / Extroversion (E)
[0 0 0 ... 0 0 0]
NS: Intuition (N) / Sensing (S)
[0 0 0 ... 1 0 1]
FT: Feeling (F) / Thinking (T)
[1 1 0 ... 0 1 0]
JP: Judging (J) / Perceiving (P)
[1 1 1 ... 0 0 0]
The final Accuracy is : 0.27062478425957887
Weighted Precision: 57.99%
Macro Precision: 50.22%
Weighted Recall: 65.10%
Macro Recall: 51.35%
Weighted F1score: 60.77%
Macro F1score: 49.95%


#### kNN

In [38]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, list_personality, test_size=0.33, random_state=42)


final_pred = np.zeros((X_test.shape[0], 4)) # 紀錄 4 個 model 分別預測病combine後的 MBTI 結果

# XGBoost Model create
for l in range(len(personality_type)):
    
    Y = y_train[:,l]
    

    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train,y_train[:,l])
    y_pred = knn.predict(X_test)

    # 將四個預測結果合併成最後 MBTI 結果
    for j in range(len(y_pred)):
        final_pred[j][l] = y_pred[j]


    # predictions = [round(value) for value in y_pred]
    # # evaluate predictions
    # accuracy = accuracy_score(y_test, predictions)
    
    print(personality_type[l])
    print(y_pred)

accuracy = accuracy_score(y_test, final_pred)
print(f'The final Accuracy is : {accuracy}')

precision_we = precision_score(y_test, final_pred, average='weighted')
print("Weighted Precision: %.2f%%" % (precision_we * 100.0))
precision_ma = precision_score(y_test, final_pred, average='macro')
print("Macro Precision: %.2f%%" % (precision_ma * 100.0))

recall_we = recall_score(y_test, final_pred, average='weighted')
print("Weighted Recall: %.2f%%" % (recall_we * 100.0))
recall_ma = recall_score(y_test, final_pred, average='macro')
print("Macro Recall: %.2f%%" % (recall_ma * 100.0))

f1score_we = f1_score(y_test, final_pred, average='weighted')
print("Weighted F1score: %.2f%%" % (f1score_we * 100.0))
f1score_ma = f1_score(y_test, final_pred, average='macro')
print("Macro F1score: %.2f%%" % (f1score_ma * 100.0))


IE: Introversion (I) / Extroversion (E)
[0 0 0 ... 0 0 1]
NS: Intuition (N) / Sensing (S)
[0 0 0 ... 0 0 0]
FT: Feeling (F) / Thinking (T)
[1 1 1 ... 0 1 1]
JP: Judging (J) / Perceiving (P)
[1 1 1 ... 0 1 0]
The final Accuracy is : 0.2599240593717639
Weighted Precision: 58.03%
Macro Precision: 52.68%
Weighted Recall: 56.57%
Macro Recall: 42.35%
Weighted F1score: 55.35%
Macro F1score: 43.62%


#### Decision Tree

In [37]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn import tree


X_train, X_test, y_train, y_test = train_test_split(X, list_personality, test_size=0.33, random_state=42)


final_pred = np.zeros((X_test.shape[0], 4)) # 紀錄 4 個 model 分別預測病combine後的 MBTI 結果

# XGBoost Model create
for l in range(len(personality_type)):
    
    Y = y_train[:,l]
    

    clf = tree.DecisionTreeClassifier()
    clf = clf.fit(X_train, y_train[:,l])
    y_pred = clf.predict(X_test)

    # 將四個預測結果合併成最後 MBTI 結果
    for j in range(len(y_pred)):
        final_pred[j][l] = y_pred[j]


    # predictions = [round(value) for value in y_pred]
    # # evaluate predictions
    # accuracy = accuracy_score(y_test, predictions)
    
    print(personality_type[l])
    print(y_pred)

accuracy = accuracy_score(y_test, final_pred)
print(f'The final Accuracy is : {accuracy}')

precision_we = precision_score(y_test, final_pred, average='weighted')
print("Weighted Precision: %.2f%%" % (precision_we * 100.0))
precision_ma = precision_score(y_test, final_pred, average='macro')
print("Macro Precision: %.2f%%" % (precision_ma * 100.0))

recall_we = recall_score(y_test, final_pred, average='weighted')
print("Weighted Recall: %.2f%%" % (recall_we * 100.0))
recall_ma = recall_score(y_test, final_pred, average='macro')
print("Macro Recall: %.2f%%" % (recall_ma * 100.0))

f1score_we = f1_score(y_test, final_pred, average='weighted')
print("Weighted F1score: %.2f%%" % (f1score_we * 100.0))
f1score_ma = f1_score(y_test, final_pred, average='macro')
print("Macro F1score: %.2f%%" % (f1score_ma * 100.0))

IE: Introversion (I) / Extroversion (E)
[0 0 0 ... 0 1 1]
NS: Intuition (N) / Sensing (S)
[0 0 0 ... 0 0 0]
FT: Feeling (F) / Thinking (T)
[0 1 1 ... 0 1 1]
JP: Judging (J) / Perceiving (P)
[0 0 0 ... 0 0 0]
The final Accuracy is : 0.17500862961684502
Weighted Precision: 52.01%
Macro Precision: 43.23%
Weighted Recall: 50.98%
Macro Recall: 42.73%
Weighted F1score: 51.48%
Macro F1score: 42.97%


#### 